import { useEffect,useRef,useState,type FormEvent } from 'react';
import type { PublicGameState } from '@vtt/shared';
import { GameCanvas } from './game/GameCanvas';
import { clearSession,connectSocket,loadSession,saveSession,type Session,type VttSocket } from './networking/socket';

async function post(url:string,body:unknown){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error??'Request failed');return d;}

function Lobby({onSession}:{onSession:(s:Session)=>void}){const[mode,setMode]=useState<'create'|'join'>('create'),[name,setName]=useState('GM'),[room,setRoom]=useState('Friday Night Adventure'),[code,setCode]=useState(''),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();try{setError('');const d=mode==='create'?await post('/api/rooms',{roomName:room,gmName:name}):await post('/api/rooms/join',{joinCode:code,playerName:name});onSession({roomId:d.roomId,sessionToken:d.sessionToken,playerId:d.playerId});}catch(err){setError(err instanceof Error?err.message:'Request failed');}}return <main className="lobby"><form className="card" onSubmit={submit}><div className="eyebrow">VTT for Friends · v0.1</div><h1>Your table, in the browser.</h1><div className="tabs"><button type="button" className={mode==='create'?'active':''} onClick={()=>setMode('create')}>Create Room</button><button type="button" className={mode==='join'?'active':''} onClick={()=>{setMode('join');setName('')}}>Join Room</button></div>{mode==='create'?<label>Room name<input value={room} onChange={e=>setRoom(e.target.value)}/></label>:<label>Room code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ABC123"/></label>}<label>{mode==='create'?'GM name':'Player name'}<input value={name} onChange={e=>setName(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button className="primary">{mode==='create'?'Create as GM':'Join as Player'}</button></form></main>}

export default function App(){const[session,setSession]=useState<Session|null>(()=>loadSession()),[state,setState]=useState<PublicGameState|null>(null),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[chat,setChat]=useState(''),[dice,setDice]=useState('d20'),[initiative,setInitiative]=useState<Record<string,string>>({});const socketRef=useRef<VttSocket|null>(null);
  useEffect(()=>{if(!session)return;const s=connectSocket(session);socketRef.current=s;s.on('room:state',setState);s.on('connect',()=>s.emit('room:requestState'));s.on('connect_error',e=>setError(e.message));return()=>{s.disconnect();socketRef.current=null}},[session]);
  function accept(s:Session){saveSession(s);setSession(s)}function leave(){socketRef.current?.disconnect();clearSession();setSession(null);setState(null)}function emit(event:string,...args:any[]){const s=socketRef.current;if(!s)return;(s.emit as any)(event,...args,(r:any)=>{if(r&&!r.ok)setError(r.error)})}
  if(!session)return <Lobby onSession={accept}/>;if(!state)return <main className="lobby"><div className="card"><h2>Connecting…</h2>{error&&<p className="error">{error}</p>}<button onClick={leave}>Back</button></div></main>;
  const gm=state.self.role==='gm',selectedToken=state.tokens.find(t=>t.id===selected)??null;
  async function mapUpload(file:File){const bitmap=await createImageBitmap(file);const f=new FormData();f.append('image',file);f.append('roomId',session!.roomId);f.append('sessionToken',session!.sessionToken);f.append('mapWidth',String(bitmap.width));f.append('mapHeight',String(bitmap.height));bitmap.close();const r=await fetch('/api/uploads/map',{method:'POST',body:f});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error??'Upload failed')}
  function startCombat(){const combatants=state!.tokens.flatMap(t=>{const raw=initiative[t.id];return raw==null||raw===''?[]:[{tokenId:t.id,initiative:Number(raw)}]});emit('combat:start',{combatants})}
  return <div className="shell"><header><strong>{state.room.name}</strong><span className="pill">Room {state.room.joinCode}</span><span className="spacer"/><span>{state.self.name} · {gm?'GM':'Player'}</span><button onClick={()=>navigator.clipboard?.writeText(state.room.joinCode)}>Copy code</button><button onClick={leave}>Leave</button></header>{error&&<div className="banner">{error}<button onClick={()=>setError('')}>×</button></div>}<div className="workspace"><aside>
    <section><h3>Players</h3>{state.players.map(p=><div className="row" key={p.id}><span className={p.connected?'dot on':'dot'}/>{p.name}<small>{p.role}</small></div>)}</section>
    {gm&&<section><h3>Scene</h3><label>Map<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(f)try{await mapUpload(f)}catch(err){setError(err instanceof Error?err.message:'Upload failed')}}}/></label><label>Grid size<input type="number" min="10" max="500" value={state.scene.gridSize} onChange={e=>emit('scene:update',{gridSize:Number(e.target.value)})}/></label><div className="twocol"><label>Offset X<input type="number" value={state.scene.gridOffsetX} onChange={e=>emit('scene:update',{gridOffsetX:Number(e.target.value)})}/></label><label>Offset Y<input type="number" value={state.scene.gridOffsetY} onChange={e=>emit('scene:update',{gridOffsetY:Number(e.target.value)})}/></label></div><label className="check"><input type="checkbox" checked={state.scene.gridVisible} onChange={e=>emit('scene:update',{gridVisible:e.target.checked})}/>Show grid</label><label className="check"><input type="checkbox" checked={state.scene.snapToGrid} onChange={e=>emit('scene:update',{snapToGrid:e.target.checked})}/>Snap to grid</label></section>}
    <section><h3>Tokens</h3>{state.tokens.map(t=><button className={`tokenrow ${selected===t.id?'active':''}`} key={t.id} onClick={()=>setSelected(t.id)}><span>{t.name}</span><small>{t.hp}/{t.maxHp}</small></button>)}{gm&&<button className="primary full" onClick={()=>emit('token:create',{name:'New Token',x:state.scene.gridOffsetX,y:state.scene.gridOffsetY,width:1,height:1,imageUrl:null,hp:10,maxHp:10,ac:10,ownerId:null,hidden:false})}>+ Token</button>}</section>
    {gm&&selectedToken&&<section><h3>Edit {selectedToken.name}</h3><label>Name<input value={selectedToken.name} onChange={e=>emit('token:update',{tokenId:selectedToken.id,patch:{name:e.target.value}})}/></label><div className="threecol"><label>HP<input type="number" value={selectedToken.hp} onChange={e=>emit('token:update',{tokenId:selectedToken.id,patch:{hp:Number(e.target.value)}})}/></label><label>Max<input type="number" value={selectedToken.maxHp} onChange={e=>emit('token:update',{tokenId:selectedToken.id,patch:{maxHp:Number(e.target.value)}})}/></label><label>AC<input type="number" value={selectedToken.ac} onChange={e=>emit('token:update',{tokenId:selectedToken.id,patch:{ac:Number(e.target.value)}})}/></label></div><label>Owner<select value={selectedToken.ownerId??''} onChange={e=>emit('token:update',{tokenId:selectedToken.id,patch:{ownerId:e.target.value||null}})}><option value="">None</option>{state.players.filter(p=>p.role==='player').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="check"><input type="checkbox" checked={selectedToken.hidden} onChange={e=>emit('token:update',{tokenId:selectedToken.id,patch:{hidden:e.target.checked}})}/>Hidden</label><button className="danger full" onClick={()=>{emit('token:delete',{tokenId:selectedToken.id});setSelected(null)}}>Delete</button></section>}
  </aside><main className="canvaswrap"><GameCanvas scene={state.scene} tokens={state.tokens} self={state.self} combat={state.combat} selectedTokenId={selected} onSelectToken={setSelected} onMoveToken={(tokenId,x,y)=>emit('token:move',{tokenId,x,y})}/><div className="help">Wheel zoom · Middle drag or Space+drag pan · Drag controlled token</div></main><aside className="right"><section><h3>Combat {state.combat.active&&`· Round ${state.combat.round}`}</h3>{state.combat.active?<>{state.combat.combatants.map((c,i)=><div className={`combat ${i===state.combat.turnIndex?'current':''}`} key={c.tokenId}><span>{state.tokens.find(t=>t.id===c.tokenId)?.name??'Unknown'}</span><strong>{c.initiative}</strong></div>)}{gm&&<div className="actions"><button onClick={()=>emit('combat:previous')}>◀</button><button className="primary" onClick={()=>emit('combat:next')}>Next ▶</button><button className="danger" onClick={()=>emit('combat:end')}>End</button></div>}</>:gm?<>{state.tokens.map(t=><label className="initiative" key={t.id}>{t.name}<input type="number" value={initiative[t.id]??''} onChange={e=>setInitiative(old=>({...old,[t.id]:e.target.value}))}/></label>)}<button className="primary full" onClick={startCombat}>Start Combat</button></>:<p className="muted">Waiting for GM.</p>}</section></aside></div>
  <footer><div className="log">{state.chat.map(m=><div key={m.id} className={`msg ${m.type}`}><strong>{m.playerName}</strong><span>{m.content}</span></div>)}</div><div className="inputs"><form onSubmit={e=>{e.preventDefault();if(chat.trim()){emit('chat:send',{content:chat.trim()});setChat('')}}}><input value={chat} onChange={e=>setChat(e.target.value)} placeholder="Message…"/><button>Send</button></form><form onSubmit={e=>{e.preventDefault();emit('dice:roll',{expression:dice})}}><input value={dice} onChange={e=>setDice(e.target.value)}/><button>Roll</button></form></div></footer></div>
}
